### ISSUE TITLE
imporve UX in updates

### ISSUE THREAD

**Issue by semyon-dev** [BiteDasher/sakuri#1]
Please make suggestions about what exactly is being updated - where is pkgrel and where is just package updates?
![image](https://user-images.githubusercontent.com/38791501/80256663-d4602880-8687-11ea-88d9-54b3fa2ba4fd.png)

**Comment by BiteDasher** [comment]
Fixed in commit `0120ac6`

**Comment by semyon-dev** [comment]
thanks
